### PR TITLE
Add npm badge

### PR DESCRIPTION
**Pull request by SimenB**
Also use badges from shields.io.

Maybe remove the stable note as well?

How it looks like: https://github.com/SimenB/backbone.layoutmanager/blob/badges/README.md

### CODE REVIEW

**Comment by tbranyen** [comment]
I know some people like having badges on the same level as the project name, but would you mind moving them down to where they were before?

The stable note is there so that you know at a quick glance what the latest published version is.  Any particular reason why you think we should remove it?

**Comment by SimenB** [comment]
Sure I can move it :smile: 

The reason the stable note is not needed is that the npm badge show the version

**Comment by tbranyen** [comment]
Ohhhh good point! I like :)

**Comment by SimenB** [comment]
@tbranyen Updates

**Comment by tbranyen** [comment]
Thanks!

**Pull request merged**
